api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    dapr:
      appId: changefeedfunctions
      appPort: 8080
      enabled: true
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--cosmos
        keyVaultUrl: '{{ .Env.SERVICE_BINDING_KVF2EDECB5_ENDPOINT }}secrets/connectionString'
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: changefeedfunctions
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Aspire__Azure__Storage__Blobs__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
          - name: Aspire__Azure__Storage__Queues__AzureWebJobsStorage__ServiceUri
            value: '{{ .Env.STORAGE_QUEUEENDPOINT }}'
          - name: AzureFunctionsJobHost__telemetryMode
            value: OpenTelemetry
          - name: AzureWebJobsStorage__blobServiceUri
            value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
          - name: AzureWebJobsStorage__queueServiceUri
            value: '{{ .Env.STORAGE_QUEUEENDPOINT }}'
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet-isolated
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__cosmos
            secretRef: connectionstrings--cosmos
    scale:
      minReplicas: 1
tags:
  azd-service-name: changefeedfunctions
  aspire-resource-name: changefeedfunctions
